### ISSUE TITLE
Unable to export story collection

### ISSUE THREAD

**Issue by toddbarr** [pdfernhout/narrafirma#46] opened 2022-03-14 15:44 UTC
Hello NarraFirma community,

I would like to export a story collection from last summer. I am logged in to the NarraFirma platform…but when I click on the button “export story collection…” nothing happens. Can anyone shed some light?

With thanks for considering,
Todd.

**Comment by cfkurtz** [comment] 2022-03-14 17:40
Hi Todd, thanks for posting the issue. My first guess is that this is the same can't-export issue another user reported (via email) a few weeks ago. I fixed it in version 1.5.11. Could you update your installation of NarraFirma to 1.5.11 (or, better, to the latest version, 1.5.14 at this moment) and see if that fixes the problem?

If that doesn't work, could you send me an email (to cfkurtz@cfkurtz.com) so you can help me replicate the problem?

**Comment by cfkurtz** [comment] 2022-03-16 14:45
I have issued a tentative fix for this issue in version 1.5.15. I will keep this issue open until I hear back from you (via email) that it worked for you. (But it should!)

**Comment by cfkurtz** [comment] 2022-03-16 18:31
Okay, I heard back from Todd that the issue is fixed and his data exported correctly. He suggested that I post the explanation I gave him (in email) here, so other people could see it if they're looking at a similar issue. So here it is:

---

What seems to have happened was, you created a question of the type "checkboxes," then added some stories, then  changed the question type to "select," then added more stories. An  answer to a "select" question is stored as a string (of characters), and a set of answers to a "checkboxes" questions is stored as an object (with key-value pairs). So NF looked for a string, found an object, and got stuck.

I have changed the export code to more elegantly deal with this particular data mismatch. NF will now post warnings to the development console that it found multi-choice data when it was looking for single-choice data, and then export the data anyway, instead of just choking. (Which is bad.)

If you update your NF version (to 1.5.15) you should be able to export your stories correctly. 

However, I only changed how NF deals with this one particular mismatch. There are plenty of other mismatches possible. In general, it is best not to change question types after stories have been collected, for exactly this reason: NF expects the data to match the questions. I don't know, for example, what happens to graphs and statistics when this assumption is broken. Some counts could be off.

It might be a good wish-list item to think about how NF might in the future accommodate every possible variety of mismatch between questions and data. But it might take a long time to do that correctly, and in some cases it might be hard to guess how to interpret the data.

**Closed as completed by cfkurtz** 2022-03-16 18:31 UTC
